const wordList = [
{word:"	אה (כן, הבנתי)	", description: "	אַאה	", unit: 1},
{word:"	איזה	", description: "	אַי	", unit: 1},
{word:"	איך	", description: "	כִּיף	", unit: 1},
{word:"	איפה	", description: "	וֵין	", unit: 1},
{word:"	אנחנו	", description: "	אִחנַא	", unit: 1},
{word:"	אני	", description: "	אַנַא	", unit: 1},
{word:"	את	", description: "	אִנתִ	", unit: 1},
{word:"	אתה	", description: "	אִנתִ	", unit: 1},
{word:"	אתם	", description: "	אִנתוּ	", unit: 1},
{word:"	אתן	", description: "	אִנתֶן	", unit: 1},
{word:"	ב	", description: "	פִי	", unit: 1},
{word:"	באיזה	", description: "	פִי אַי	", unit: 1},
{word:"	בואי תכירי	", description: "	תַעַאלִי תעַרַפִי	", unit: 1},
{word:"	בית, בתים	", description: "	בֵּית, בּיוּת	", unit: 1},
{word:"	גם	", description: "	כַּמַאן	", unit: 1},
{word:"	גר, גרים	", description: "	סַאכֶּן, סַאכּנִין	", unit: 1},
{word:"	גרה, גרות	", description: "	סַאכּנֶה, סַאכּנַאת	", unit: 1},
{word:"	הוא	", description: "	הֻוַ	", unit: 1},
{word:"	היא	", description: "	הִיַ	", unit: 1},
{word:"	הם	", description: "	הֻמֶ	", unit: 1},
{word:"	הן	", description: "	הִנֶ	", unit: 1},
{word:"	השבח לאל	", description: "	אלחַמדִללַה	", unit: 1},
{word:"	זאת	", description: "	הַאדִ'י	", unit: 1},
{word:"	זה	", description: "	הַאדַ'א	", unit: 1},
{word:"	כן	", description: "	אַיוַה	", unit: 1},
{word:"	לא	", description: "	לַא	", unit: 1},
{word:"	מ, מן	", description: "	מִן	", unit: 1},
{word:"	מאיפה	", description: "	מִן וֵין	", unit: 1},
{word:"	מדבר/ת (אני)	", description: "	בַּחכִּי	", unit: 1},
{word:"	מה	", description: "	שוּ	", unit: 1},
{word:"	מה שלומךְ?	", description: "	כִּיף חַאלֶכּ?	", unit: 1},
{word:"	מי	", description: "	מִין	", unit: 1},
{word:"	עיר, ערים	", description: "	בַּלַד	מַדִינֶה, מֻדֻן	", unit: 1},
{word:"	ערבי, ערבים	", description: "	עַרַבִּי, עַרַבּ	", unit: 1},
{word:"	ערבית (שפה)	", description: "	עַרַבִּי	", unit: 1},
{word:"	קרוב ל	", description: "	קַרִיבּ מִן	", unit: 1},
{word:"	רחוב, רחובות	", description: "	שַארֶע, שַוַארֶע	", unit: 1},
{word:"	שכן, שכנים	", description: "	גַ'אר, גִ'ירַאן	", unit: 1},
{word:"	שכנה, שכנות	", description: "	גַ'ארַה, גַ'ארַאת	", unit: 1},
{word:"	שלום	", description: "	מַרחַבַּא	אַהלַן	", unit: 1},
{word:"	שלום (תשובה)	", description: "	מַרחַבּתֵין	אַהלֵין	", unit: 1},
{word:"	שם, שמות	", description: "	אִסֶם, אַסמַאא / אַסַאמִי	", unit: 1},

{word:"	אבא של ...	", description: "	אַבּוּ	", unit: 2},
{word:"	אח, אחים	", description: "	אַח'וּ, אִח'וֶה	", unit: 2},
{word:"	אחד	", description: "	וַאחַד	", unit: 2},
{word:"	אחי	", description: "	אַח'וּי	", unit: 2},
{word:"	אחת	", description: "	וַחַדֶה	", unit: 2},
{word:"	איך	", description: "	כִּיף	", unit: 2},
{word:"	אין	", description: "	פִש, מַפִש	", unit: 2},
{word:"	אם, אמא	", description: "	אִם	", unit: 2},
{word:"	אנו מודים לאללה	", description: "	נֻשכֹּר אַללַה	", unit: 2},
{word:"	אפס	", description: "	סִֿפר	", unit: 2},
{word:"	ארבעה	", description: "	אַרבַּעַה	", unit: 2},
{word:"	אשה, נשים	", description: "	מַרַה, נִסוַאן	", unit: 2},
{word:"	בוקר אור	", description: "	סַבַּאחִ (אל)נוּר	", unit: 2},
{word:"	בוקר טוב	", description: "	סַבַּאחִ (א)לחֵ'יר	", unit: 2},
{word:"	בן, בנים	", description: "	אִבֶּן, ולַאד (אַבּנַאא)	", unit: 2},
{word:"	בסדר	", description: "	מַאשִי, תַמַאם	", unit: 2},
{word:"	בעל	", description: "	ג'וֹז	", unit: 2},
{word:"	בת, בנות	", description: "	בִּנת, בַּנַאת	", unit: 2},
{word:"	גדול, גדולים	", description: "	כּבִּיר, כּבַּאר	", unit: 2},
{word:"	גיל	", description: "	עֻמֻר	", unit: 2},
{word:"	דבר, דברים	", description: "	אִשִי, אַשיַאא	", unit: 2},
{word:"	חולה, חולים	", description: "	מרִיד, מרַאד	 עַיַאן, עַיַאנִין   	", unit: 2},
{word:"	חמישה	", description: "	חַ'מסֶה	", unit: 2},
{word:"	יום, ימים	", description: "	יוֹם, אַיַאם	", unit: 2},
{word:"	ילד, ילדים	", description: "	וַלַד, ולַאד	", unit: 2},
{word:"	יפֶה, יפים	", description: "	חִלִו, חִלוִין	", unit: 2},
{word:"	ירושלים	", description: "	אִלקֻדס	", unit: 2},
{word:"	ירושלמי, ירושלמים	", description: "	קֻדסִי, קֻדסִיִין	", unit: 2},
{word:"	יש לי	", description: "	עִנדִי	", unit: 2},
{word:"	כאן	", description: "	הוֹן	", unit: 2},
{word:"	כל	", description: "	כֻּל	", unit: 2},
{word:"	כלומר	", description: "	יַענִי	", unit: 2},
{word:"	כמה (גיל, כסף, זמן)	", description: "	קַדֵיש	", unit: 2},
{word:"	מה חדש	", description: "	שוּ (א)לאַח'בַּאר	", unit: 2},
{word:"	מכנים אותי	", description: "	בִּנַאדוּנִי	", unit: 2},
{word:"	מספר, מספרים	", description: "	רַקַם, אַרקַאם	", unit: 2},
{word:"	מצב	", description: "	חַאל	", unit: 2},
{word:"	מרוצֶה, מרוצים	", description: "	מַבּסוּט, מַבּסוּטִין	", unit: 2},
{word:"	נסיך	", description: "	אַמִיר	", unit: 2},
{word:"	עייף, עייפים	", description: "	תַעבַּאן, תַעבַּאנִין	", unit: 2},
{word:"	עשרה	", description: "	עַשַרַה	", unit: 2},
{word:"	קטן, קטנים	", description: "	זרִ'יר, זרַ'אר	", unit: 2},
{word:"	קצת, מעט	", description: "	שוַי	", unit: 2},
{word:"	רופא, רופאים	", description: "	דַכּתוֹר, דַכַּאתרַה	", unit: 2},
{word:"	שבעה	", description: "	סַבּעַה	", unit: 2},
{word:"	שלושה	", description: "	תַ 'לַאתֶ'ה	", unit: 2},
{word:"	שמונה	", description: "	תַ 'מַאניֶה	", unit: 2},
{word:"	שנה, שנים	", description: "	סַנֶה, סנִין	", unit: 2},
{word:"	שניים	", description: "	ת'נֵין	", unit: 2},
{word:"	ששה	", description: "	סִתֶה	", unit: 2},
{word:"	שתיים	", description: "	תִ'נתֵין	", unit: 2},
{word:"	תשעה	", description: "	תִסעַה	", unit: 2}
]; 