const wordList = [
// unit 1
{word:"	אה (כן, הבנתי)	", description: "	אַאה	", unit: 1},
{word:"	איזה	", description: "	אַי	", unit: 1},
{word:"	איך	", description: "	כִּיף	", unit: 1},
{word:"	איפה	", description: "	וֵין	", unit: 1},
{word:"	אנחנו	", description: "	אִחנַא	", unit: 1},
{word:"	אני	", description: "	אַנַא	", unit: 1},
{word:"	את	", description: "	אִנתִ	", unit: 1},
{word:"	אתה	", description: "	אִנתִ	", unit: 1},
{word:"	אתם	", description: "	אִנתוּ	", unit: 1},
{word:"	אתן	", description: "	אִנתֶן	", unit: 1},
{word:"	ב	", description: "	פִי	", unit: 1},
{word:"	באיזה	", description: "	פִי אַי	", unit: 1},
{word:"	בואי תכירי	", description: "	תַעַאלִי תעַרַפִי	", unit: 1},
{word:"	בית, בתים	", description: "	בֵּית, בּיוּת	", unit: 1},
{word:"	גם	", description: "	כַּמַאן	", unit: 1},
{word:"	גר, גרים	", description: "	סַאכֶּן, סַאכּנִין	", unit: 1},
{word:"	גרה, גרות	", description: "	סַאכּנֶה, סַאכּנַאת	", unit: 1},
{word:"	הוא	", description: "	הֻוַ	", unit: 1},
{word:"	היא	", description: "	הִיַ	", unit: 1},
{word:"	הם	", description: "	הֻמֶ	", unit: 1},
{word:"	הן	", description: "	הִנֶ	", unit: 1},
{word:"	השבח לאל	", description: "	אלחַמדִללַה	", unit: 1},
{word:"	זאת	", description: "	הַאדִ'י	", unit: 1},
{word:"	זה	", description: "	הַאדַ'א	", unit: 1},
{word:"	כן	", description: "	אַיוַה	", unit: 1},
{word:"	לא	", description: "	לַא	", unit: 1},
{word:"	מ, מן	", description: "	מִן	", unit: 1},
{word:"	מאיפה	", description: "	מִן וֵין	", unit: 1},
{word:"	מדבר/ת (אני)	", description: "	בַּחכִּי	", unit: 1},
{word:"	מה	", description: "	שוּ	", unit: 1},
{word:"	מה שלומךְ?	", description: "	כִּיף חַאלֶכּ?	", unit: 1},
{word:"	מי	", description: "	מִין	", unit: 1},
{word:"	עיר, ערים	", description: "	בַּלַד	מַדִינֶה, מֻדֻן	", unit: 1},
{word:"	ערבי, ערבים	", description: "	עַרַבִּי, עַרַבּ	", unit: 1},
{word:"	ערבית (שפה)	", description: "	עַרַבִּי	", unit: 1},
{word:"	קרוב ל	", description: "	קַרִיבּ מִן	", unit: 1},
{word:"	רחוב, רחובות	", description: "	שַארֶע, שַוַארֶע	", unit: 1},
{word:"	שכן, שכנים	", description: "	גַ'אר, גִ'ירַאן	", unit: 1},
{word:"	שכנה, שכנות	", description: "	גַ'ארַה, גַ'ארַאת	", unit: 1},
{word:"	שלום	", description: "	מַרחַבַּא	אַהלַן	", unit: 1},
{word:"	שלום (תשובה)	", description: "	מַרחַבּתֵין	אַהלֵין	", unit: 1},
{word:"	שם, שמות	", description: "	אִסֶם, אַסמַאא / אַסַאמִי	", unit: 1},

// unit 2
{word:"	אבא של ...	", description: "	אַבּוּ	", unit: 2},
{word:"	אח, אחים	", description: "	אַח'וּ, אִח'וֶה	", unit: 2},
{word:"	אחד	", description: "	וַאחַד	", unit: 2},
{word:"	אחי	", description: "	אַח'וּי	", unit: 2},
{word:"	אחת	", description: "	וַחַדֶה	", unit: 2},
{word:"	איך	", description: "	כִּיף	", unit: 2},
{word:"	אין	", description: "	פִש, מַפִש	", unit: 2},
{word:"	אם, אמא	", description: "	אִם	", unit: 2},
{word:"	אנו מודים לאללה	", description: "	נֻשכֹּר אַללַה	", unit: 2},
{word:"	אפס	", description: "	סִֿפר	", unit: 2},
{word:"	ארבעה	", description: "	אַרבַּעַה	", unit: 2},
{word:"	אשה, נשים	", description: "	מַרַה, נִסוַאן	", unit: 2},
{word:"	בוקר אור	", description: "	סַבַּאחִ (אל)נוּר	", unit: 2},
{word:"	בוקר טוב	", description: "	סַבַּאחִ (א)לחֵ'יר	", unit: 2},
{word:"	בן, בנים	", description: "	אִבֶּן, ולַאד (אַבּנַאא)	", unit: 2},
{word:"	בסדר	", description: "	מַאשִי, תַמַאם	", unit: 2},
{word:"	בעל	", description: "	ג'וֹז	", unit: 2},
{word:"	בת, בנות	", description: "	בִּנת, בַּנַאת	", unit: 2},
{word:"	גדול, גדולים	", description: "	כּבִּיר, כּבַּאר	", unit: 2},
{word:"	גיל	", description: "	עֻמֻר	", unit: 2},
{word:"	דבר, דברים	", description: "	אִשִי, אַשיַאא	", unit: 2},
{word:"	חולה, חולים	", description: "	מרִיד, מרַאד	 עַיַאן, עַיַאנִין   	", unit: 2},
{word:"	חמישה	", description: "	חַ'מסֶה	", unit: 2},
{word:"	יום, ימים	", description: "	יוֹם, אַיַאם	", unit: 2},
{word:"	ילד, ילדים	", description: "	וַלַד, ולַאד	", unit: 2},
{word:"	יפֶה, יפים	", description: "	חִלִו, חִלוִין	", unit: 2},
{word:"	ירושלים	", description: "	אִלקֻדס	", unit: 2},
{word:"	ירושלמי, ירושלמים	", description: "	קֻדסִי, קֻדסִיִין	", unit: 2},
{word:"	יש לי	", description: "	עִנדִי	", unit: 2},
{word:"	כאן	", description: "	הוֹן	", unit: 2},
{word:"	כל	", description: "	כֻּל	", unit: 2},
{word:"	כלומר	", description: "	יַענִי	", unit: 2},
{word:"	כמה (גיל, כסף, זמן)	", description: "	קַדֵיש	", unit: 2},
{word:"	מה חדש	", description: "	שוּ (א)לאַח'בַּאר	", unit: 2},
{word:"	מכנים אותי	", description: "	בִּנַאדוּנִי	", unit: 2},
{word:"	מספר, מספרים	", description: "	רַקַם, אַרקַאם	", unit: 2},
{word:"	מצב	", description: "	חַאל	", unit: 2},
{word:"	מרוצֶה, מרוצים	", description: "	מַבּסוּט, מַבּסוּטִין	", unit: 2},
{word:"	נסיך	", description: "	אַמִיר	", unit: 2},
{word:"	עייף, עייפים	", description: "	תַעבַּאן, תַעבַּאנִין	", unit: 2},
{word:"	עשרה	", description: "	עַשַרַה	", unit: 2},
{word:"	קטן, קטנים	", description: "	זרִ'יר, זרַ'אר	", unit: 2},
{word:"	קצת, מעט	", description: "	שוַי	", unit: 2},
{word:"	רופא, רופאים	", description: "	דַכּתוֹר, דַכַּאתרַה	", unit: 2},
{word:"	שבעה	", description: "	סַבּעַה	", unit: 2},
{word:"	שלושה	", description: "	תַ 'לַאתֶ'ה	", unit: 2},
{word:"	שמונה	", description: "	תַ 'מַאניֶה	", unit: 2},
{word:"	שנה, שנים	", description: "	סַנֶה, סנִין	", unit: 2},
{word:"	שניים	", description: "	ת'נֵין	", unit: 2},
{word:"	ששה	", description: "	סִתֶה	", unit: 2},
{word:"	שתיים	", description: "	תִ'נתֵין	", unit: 2},
{word:"	תשעה	", description: "	תִסעַה	", unit: 2},

// Unit 3
{word:"	אבא (פנייה)	", description: "	יַאבַּא	", unit: 3},
{word:"	אבי	", description: "	אַבּוּי	", unit: 3},
{word:"	איזה	", description: "	אַי	", unit: 3},
{word:"	אללה יתן לךָ בריאות	", description: "	אַללַה יִעטִיכּ (א)לעַאפיֶה	", unit: 3},
{word:"	אללה יתן גם לך בריאות (תשובה)	", description: "	אַללַה יִעַאפִיכּ	", unit: 3},
{word:"	אמור	", description: "	קוּל	", unit: 3},
{word:"	אצל	", description: "	עִנד	", unit: 3},
{word:"	ארבעים	", description: "	אַרבּעִין	", unit: 3},
{word:"	באמת	", description: "	עַן-גַ'ד	", unit: 3},
{word:"	בבקשה (אתה)	", description: "	תפַדל	", unit: 3},
{word:"	בוא	", description: "	תַעַאל	", unit: 3  },
{word:"	בן דוד, בני דודים	", description: "	אִבֶּן עַם, ולַאד עַם	", unit: 3  },
{word:"	בפנים	", description: "	גֻ'וַה	", unit: 3},
{word:"	דוד, דודים (מצד האב)	", description: "	עַם, עמַאם	", unit: 3},
{word:"	הלו	", description: "	אַלוֹ	", unit: 3},
{word:"	זאת	", description: "	הַאיִ	", unit: 3},
{word:"	חבר, חברים	", description: "	סַאחֶבּ, סחַאבּ	", unit: 3},
{word:"	חזר	", description: "	רִגֶ'ע	", unit: 3},
{word:"	חמישים	", description: "	חַ׳מסִין	", unit: 3},
{word:"	טוב, טובים	", description: "	מנִיח, מנַאח	", unit: 3},
{word:"	טוב יותר	", description: "	אַחסַן	", unit: 3},
{word:"	טלויזיה	", description: "	תִלפִזיוֹן	", unit: 3},
{word:"	יש (ל)	", description: "	עִנד	", unit: 3},
{word:"	כל הכבוד	", description: "	כֻּלִ (א)לִאחתִרַאם	", unit: 3},
{word:"	כמה	", description: "	כַּם / אַכַּם	", unit: 3},
{word:"	לא	", description: "	מִש / מֻש	", unit: 3},
{word:"	לא (תשובה קצרה)	", description: "	לַא, לַע	", unit: 3},
{word:"	לאן	", description: "	לַוֵין	", unit: 3},
{word:"	ליד	", description: "	עִנד	", unit: 3},
{word:"	למה	", description: "	לֵיש	", unit: 3},
{word:"	מאה	", description: "	מִיֶה	", unit: 3},
{word:"	מבחן, מבחנים	", description: "	אמתִחַאן, אמתִחַאנַאת	", unit: 3},
{word:"	מה	", description: "	אֵיש / שוּ	", unit: 3},
{word:"	מחר	", description: "	בֻּכּרַא	", unit: 3},
{word:"	מתי	", description: "	וֵינתַא / אֵימתַא	", unit: 3},
{word:"	ניכנס	", description: "	נפוּת	", unit: 3},
{word:"	נכון	", description: "	סַח	", unit: 3},
{word:"	נשוי, נשואים	", description: "	מִתגַ'וֶז, מִתגַ'וזִין	", unit: 3},
{word:"	נתחיל	", description: "	נִבּדַא	", unit: 3},
{word:"	סופרמרקט	", description: "	סוּבֶּרמַארכֶּת	", unit: 3},
{word:"	עכשיו	", description: "	הַסַא	", unit: 3},
{word:"	עשרים	", description: "	עִשרִין	", unit: 3},
{word:"	רווק, רווקים	", description: "	עַזַאבִּי, עַזַאבִּיִין	", unit: 3},
{word:"	שב	", description: "	אֻקעֻד	", unit: 3},
{word:"	שבעים	", description: "	סַבּעִין	", unit: 3},
{word:"	שישים	", description: "	סִתִין	", unit: 3},
{word:"	שלום	", description: "	אִ (ל)סַלַאםֻ עַלֵיכֹּם	", unit: 3},
{word:"	שלום (תשובה)	", description: "	וּעַלֵיכֹּםֻ (אל)סַלַאם	", unit: 3},
{word:"	שלושים	", description: "	תַ׳לַאתִ׳ין	", unit: 3},
{word:"	שמונים	", description: "	תַ׳מַאנִין	", unit: 3},
{word:"	תהיה בריא	", description: "	תִסלַם	", unit: 3},
{word:"	תשעים	", description: "	תִסעִין	", unit: 3},	
// Unit 4
{word:"	אבל, רק	", description: "בַּס	", unit: 4},
{word:"	אללה יברך אותך (תשובה)	", description: "	אַללַה יִבַּארֶכּ פִיכּ	", unit: 4},
{word:"	אללה יברך אותך	", description: "	אַללַה יִסַלמַכּ	", unit: 4},
{word:"	אללה יעניק לך אושר ופרנסה (תשובה)	", description: "	אַללַה יִנעֶם עַלֵיכּ	", unit: 4},
{word:"	אתמול	", description: "	מבַּארֶח	", unit: 4},
{word:"	בחיי, באמת	", description: "	וַאללַהִ	", unit: 4},
{word:"	ברוכים הבאים	", description: "	אַהלַן וַסַהלַן	", unit: 4},
{word:"	ברוכים הנמצאים (תשובה)	", description: "	אַהלַן פִיכֹּם	", unit: 4},
{word:"	גדול יותר, הכי גדול	", description: "	אַכּבַּר	", unit: 4},
{word:"	דעה, דעות	", description: "	רַאי, אַרַאא	", unit: 4},
{word:"	הרבה, רבים	", description: "	כּתִ'יר, כּתַ'אר	", unit: 4},
{word:"	וידיך [יבורכו] (תשובה)	", description: "	וּאִידֵיכּ	", unit: 4},
{word:"	חכה	", description: "	אסתַנַא	", unit: 4},
{word:"	טלפון, טלפונים	", description: "	תַלַפוֹן, תַלַפוֹנַאת	", unit: 4},
{word:"	טעים יותר, הכי טעים	", description: "	אַטיַבּ / אַזכַּא	", unit: 4},
{word:"	יבורך פיך	", description: "	יִסלַם תִ'מַכּ	", unit: 4},
{word:"	יבורכו ידיך	", description: "	יִסלַמוּ אִידֵיכּ	", unit: 4},
{word:"	יותר	", description: "	אַכּתַ'ר	", unit: 4},
{word:"	יפה יותר, הכי יפה	", description: "	אַחלַא	", unit: 4},
{word:"	כמובן	", description: "	טַבּעַן	", unit: 4},
{word:"	להתראות	", description: "	סַלַאמַאת	", unit: 4},
{word:"	להתראות (תשובה)	", description: "	מַעִ (אל)סַלַאמֶה	", unit: 4},
{word:"	למה	", description: "	לֵיש	", unit: 4},
{word:"	מאד	", description: "	כּתִ'יר	", unit: 4},
{word:"	מוסלמי, מוסלמים	", description: "	מֻסלִם, מֻסִלמִין	", unit: 4},
{word:"	מזל טוב	", description: "	מַבּרוּכּ	", unit: 4},
{word:"	מסור דרישת שלום ל-	", description: "	סַלֶם עַלַא	", unit: 4},
{word:"	מצוין, מצוינים	", description: "	מֻמתַאז, מֻמתַאזִין	", unit: 4},
{word:"	מרפסת, מרפסות	", description: "	בַּלכּוֹן, בַּלכּוֹנַאת	", unit: 4},
{word:"	מתוק יותר, הכי מתוק	", description: "	אַחלַא	", unit: 4},
{word:"	מתי	", description: "	וֵינתַא / אֵימתַא	", unit: 4},
{word:"	פעם, פעמים	", description: "	מַרַה, מַרַאת	", unit: 4},
{word:"	קטן יותר, הכי קטן	", description: "	אַזרַ'ר	", unit: 4},
{word:"	קפה	", description: "	קַהוֶה	", unit: 4},
{word:"	קרוב יותר, הכי קרוב	", description: "	אַקרַבּ	", unit: 4},
{word:"	שוקולד	", description: "	שֻכֻּלַאתַה	", unit: 4},
{word:"	שָם	", description: "	הֻנַאכּ	", unit: 4},
{word:"	שני, אחר, נוסף	", description: "	תַ'אנִי	", unit: 4},
{word:"	שְתה	", description: "	אִשרַבּ	", unit: 4},
{word:"	תה	", description: "	שַאי	", unit: 4},
{word:"	תהיה בריא	", description: "	סַלַאמתַכּ	", unit: 4},
{word:"	תודה (שתזכה לארח הרבה)	", description: "	עַמַאר	", unit: 4},
{word:"	תודה, תבורך	", description: "	תִסלַם	", unit: 4},
{word:"	תתחדש (על תספורת)	", description: "	נַעִימַן	", unit: 4},
// Unit 5
{word:"	אדום	", description: "	אַחמַר	"},
{word:"	אדומה	", description: "	חַמרַא	"},
{word:"	אהוב ליבי	", description: "	חַבִּיבּ קַלבִּי	"},
{word:"	אהוב, אהובים	", description: "	חַבִּיבּ, חַבַּאיֶבּ	"},
{word:"	אוטובוס, אוטובוסים	", description: "	בַּאסֿ , בַּאסַֿאת	"},
{word:"	אחד עשר	", description: "	חדַאש	"},
{word:"	אחות, אחיות	", description: "	אֻח'ת, חַ'וַאת	"},
{word:"	אחת, מישהי	", description: "	וַחַדֶה	"},
{word:"	אלה	", description: "	הַד'וֹל	"},
{word:"	אמר	", description: "	קַאל	"},
{word:"	ארבעה עשר	", description: "	אַרבַּעטַאש	"},
{word:"	בא	", description: "	אַגַ'א	"},
{word:"	בית, בתים	", description: "	דַאר, דוּר	"},
{word:"	ג'קט, ג'קטים	", description: "	גַ'אכֵּית, גַ'אכֵּיתַאת	"},
{word:"	דגל, דגלים	", description: "	עַלַם, אַעלַאם	"},
{word:"	דוד, דודים (מצד האם)	", description: "	חַ'אל, ח'וַאל	"},
{word:"	הורים	", description: "	אַהֶל	"},
{word:"	היה	", description: "	כַּאן	"},
{word:"	הלך	", description: "	רַאח	"},
{word:"	וואו	", description: "	וַלַאוְ	"},
{word:"	חבל שלא דיברנו על מיליון דולר  	", description: "	לַוְ גִ'בּנַא סִירֶת  מַליוֹן דוֹלַאר 	"},
{word:"	חדש, חדשים	", description: "	ג'דִיד, ג'דַאד	"},
{word:"	חמישה עשר	", description: "	חַ’מִסטַאש	"},
{word:"	ירוק	", description: "	אַח'דַֿר	"},
{word:"	ירוקה	", description: "	חַ'דֿרַא	"},
{word:"	ישב	", description: "	קַעַד	"},
{word:"	כחול	", description: "	אַזרַק	"},
{word:"	כחולה	", description: "	זַרקַא	"},
{word:"	כיף לך	", description: "	נִיַאלֶכּ	"},
{word:"	כמה	", description: "	כַּם / אַכַּם	"},
{word:"	לב, לבבות	", description: "	קַלבּ, קֻלוּבּ	"},
{word:"	לבן	", description: "	אַבּיַדֿ	"},
{word:"	לבנה	", description: "	בֵּידַֿא	"},
{word:"	מוסיקה	", description: "	מוּסִיקַא	"},
{word:"	מכונית, מכוניות	", description: "	סַיַّארַה, סַיַّארַאת	"},
{word:"	מכנסיים	", description: "	בַּנטַלוֹן, בַּנטַלוֹנַאת 	"},
{word:"	מסגד, מסגדים	", description: "	מַסגֶ'ד, מַסַאגֶ'ד	"},
{word:"	מסר דש	", description: "	סַלַّם עַלַא	"},
{word:"	מסתובב (אתה)	", description: "	בִּתלַפלֶף	"},
{word:"	משפחה, משפחות	", description: "	אַהֶל, אַהַאלִי, עֵילֶה, עֵילַאת	"},
{word:"	נכד, נכדים	", description: "	חַפִיד, אַחפַאד	"},
{word:"	נכנס	", description: "	פַאת	"},
{word:"	סבא, סבים	", description: "	סִיד, סיַאד	"},
{word:"	סבתא, סבתות	", description: "	סִתّ, סִתַّאת	"},
{word:"	עין, עיניים	", description: "	עֵין, עיוּן	"},
{word:"	עִם	", description: "	מַע	"},
{word:"	צבע, צבעים	", description: "	לוֹן, אַלוַאן	"},
{word:"	צהוב	", description: "	אַסֿפַר	"},
{word:"	צהובה	", description: "	סַֿפרַא	"},
{word:"	ראה	", description: "	שַאף	"},
{word:"	שבעה עשר	", description: "	סַבַּעטַאש	"},
{word:"	שומעת	", description: "	סַאמעַה	"},
{word:"	שוק, שווקים	", description: "	סוּק, אַסוַאק	"},
{word:"	שחור	", description: "	אַסוַד	"},
{word:"	שחורה	", description: "	סוֹדַא	"},
{word:"	שישה עשר	", description: "	סִטַّאש	"},
{word:"	של	", description: "	לַ	"},
{word:"	של מי	", description: "	לַמִין	"},
{word:"	שלושה עשר	", description: "	תַ’לַטַאש	"},
{word:"	שמונה עשר	", description: "	תַ’מַנטַאש	"},
{word:"	שמע	", description: "	סִמֶע	"},
{word:"	שְמע	", description: "	אִסמַע	"},
{word:"	שנים עשר	", description: "	טנַאש	"},
{word:"	שתה	", description: "	שִרֶבּ	"},
{word:"	תמונה, תמונות	", description: "	סֿוּרַה, סֻֿוַר	"},
{word:"	תשעה עשר	", description: "	תִסִעטַאש	"},

]; 